openapi: 3.0.1
info:
  title: CartsAPI
  description: API Definition of CartsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/carts
paths:
  ? ""
  : get:
      responses:
        default:
          description: Default response
  /export:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
